eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8282/eureka
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 0.85
    responseCacheUpdateIntervalMs: 1000
  instance:
    leaseRenewalIntervalInSeconds: 1
